#!/usr/bin/env python3
"""
Generate per-folder _INDEX.md for a topic wiki.

Walks each subfolder under `{vault}/{topic}/wiki/` and writes an `_INDEX.md`
listing every entry in that folder, grouped by tier, with a 1-line TL;DR
extracted from the entry's body.

This is Asel L2 tier-2 material: a scannable map of what lives in each
folder. Loaded when an agent is working in that area. Pairs with `_MAP.md`
(tier-1, always-loaded compressed root map — separate script).

The companion `wiki-index.py` regenerates a top-level _INDEX.md; this script
generates INDEXes inside each subfolder. Safe to delete and regenerate.

Usage
-----
    python wiki-index-per-folder.py --topic agentic-design \\
        --vault llm-wiki/wiki

    # Dry-run:
    python wiki-index-per-folder.py --topic agentic-design --dry-run

    # Cycle-contract JSON emission:
    python wiki-index-per-folder.py --topic agentic-design \\
        --cycle-id 2026-04-24-01 \\
        --run-folder docker/.../_inbox/reports/2026-04-24/2026-04-24-01/

Cycle contract
--------------
When --cycle-id and --run-folder are supplied, writes
<run-folder>/index-per-folder.json (+ .md) per the schema documented in
wiki/best-practices/cycle-step-return-format.md. Step name:
"index-per-folder".
"""

from __future__ import annotations


def _default_vault():
    """Resolve vault_root from <cwd>/.claude/wiki-config.json if present,
    otherwise fall back to "llm-wiki/wiki" relative to CWD. Per-project
    installs put wiki content at <project>/llm-wiki/wiki/."""
    import json as _json
    cfg_path = Path.cwd() / ".claude" / "wiki-config.json"
    if cfg_path.exists():
        try:
            cfg = _json.loads(cfg_path.read_text(encoding="utf-8"))
            v = cfg.get("vault_root")
            if v:
                return str(Path(v))
        except (_json.JSONDecodeError, OSError):
            pass
    return str(Path.cwd() / "llm-wiki" / "wiki")
import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
TLDR_HEADING_RE = re.compile(r"^##+\s*TL;DR\s*$", re.MULTILINE | re.IGNORECASE)
H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)

INDEX_FILE = "_INDEX.md"
MARKER = "<!-- AUTO-GENERATED by wiki-index-per-folder.py — do not hand-edit -->"
MAX_TLDR_CHARS = 180


def iso_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def parse_frontmatter(text: str) -> tuple[dict, str]:
    m = FM_RE.match(text)
    if not m:
        return {}, text
    raw, body = m.group(1), text[m.end():]
    fm = {}
    for line in raw.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        fm[key.strip()] = val.strip().strip('"').strip("'")
    return fm, body


def extract_tldr(body: str) -> str:
    """Find the first paragraph after `## TL;DR`; fall back to first paragraph."""
    m = TLDR_HEADING_RE.search(body)
    if m:
        after = body[m.end():].lstrip("\n")
        para = after.split("\n\n", 1)[0]
    else:
        # Skip the H1 title line if present; then first paragraph
        trimmed = H1_RE.sub("", body, count=1).lstrip("\n")
        para = trimmed.split("\n\n", 1)[0]
    para = " ".join(para.splitlines()).strip()
    # Strip leading blockquote markers / bold
    para = re.sub(r"^[>*\s]*", "", para)
    if len(para) > MAX_TLDR_CHARS:
        para = para[:MAX_TLDR_CHARS - 1].rstrip() + "…"
    return para or "_(no summary)_"


def tier_sort_key(tier: str) -> tuple:
    m = re.search(r"\d+", tier or "")
    if m:
        return (0, int(m.group()), tier)
    if tier == "self":
        return (1, 0, "self")
    return (2, 99, tier or "")


def collect_entries(folder: Path, wiki_root: Path) -> list[dict]:
    entries = []
    for path in sorted(folder.glob("*.md")):
        if path.name == INDEX_FILE:
            continue
        if path.name.startswith("."):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        fm, body = parse_frontmatter(text)
        title = fm.get("title") or path.stem.replace("-", " ").title()
        tier = fm.get("tier") or "?"
        confidence = fm.get("confidence") or ""
        tldr = extract_tldr(body)
        entries.append({
            "path": path,
            "filename": path.name,
            "title": title,
            "tier": tier,
            "confidence": confidence,
            "tldr": tldr,
        })
    return entries


def render_index(folder_name: str, entries: list[dict], wiki_root: Path) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    review = datetime.now().replace(month=min(datetime.now().month + 3, 12)).strftime("%Y-%m-%d")

    # Group by tier (sorted)
    by_tier: dict[str, list[dict]] = {}
    for e in entries:
        by_tier.setdefault(e["tier"], []).append(e)
    sorted_tiers = sorted(by_tier.keys(), key=tier_sort_key)

    lines = [
        "---",
        f'title: "INDEX — {folder_name}/ ({len(entries)} entries)"',
        f"date: {today}",
        f"source_url: internal://auto-generated/{folder_name}/INDEX",
        "ingested_by: wiki-index-per-folder.py",
        "tier: self",
        "confidence: high",
        f"last_reviewed: {today}",
        f"review_after: {review}",
        f"tags: [index, auto-generated, {folder_name}]",
        "---",
        "",
        MARKER,
        "",
        f"# INDEX — `{folder_name}/` ({len(entries)} entries)",
        "",
        f"Auto-generated map of the `{folder_name}/` folder. Entries grouped by tier, each with a one-line TL;DR. Scan this when you're working in this area; use full entries on demand.",
        "",
        f"Regenerated by `wiki-index-per-folder.py`. Do not hand-edit — changes will be overwritten.",
        "",
    ]

    for tier in sorted_tiers:
        tier_label = f"Tier {tier}" if tier != "self" else "Self-authored"
        group = by_tier[tier]
        lines.append(f"## {tier_label} ({len(group)})")
        lines.append("")
        # Alphabetize by title within tier
        group = sorted(group, key=lambda e: e["title"].lower())
        for e in group:
            conf_suffix = f" _({e['confidence']})_" if e["confidence"] and e["confidence"] != "high" else ""
            lines.append(f"- [{e['title']}](./{e['filename']}){conf_suffix} — {e['tldr']}")
        lines.append("")

    return "\n".join(lines) + "\n"


def process_folder(folder: Path, wiki_root: Path, dry_run: bool = False) -> dict:
    if not folder.is_dir():
        return {"folder": folder.name, "entries": 0, "changed": False, "error": "not a directory"}
    entries = collect_entries(folder, wiki_root)
    if not entries:
        return {"folder": folder.name, "entries": 0, "changed": False}

    new_content = render_index(folder.name, entries, wiki_root)
    index_path = folder / INDEX_FILE
    existing = index_path.read_text(encoding="utf-8") if index_path.exists() else ""

    # Compare ignoring the date/last_reviewed lines to avoid churn on re-runs
    def _strip_volatile(s: str) -> str:
        return re.sub(r"^(date|last_reviewed|review_after):.*$", "", s, flags=re.MULTILINE)

    changed = _strip_volatile(existing) != _strip_volatile(new_content)

    if changed and not dry_run:
        index_path.write_text(new_content, encoding="utf-8")

    return {
        "folder": folder.name,
        "entries": len(entries),
        "changed": changed,
    }


def emit_cycle_artifacts(
    run_folder: Path, cycle_id: str, results: list[dict], summary: dict
) -> None:
    run_folder.mkdir(parents=True, exist_ok=True)
    payload = {
        "skill": "wiki-index-per-folder",
        "cycle_id": cycle_id,
        "step": "index-per-folder",
        "timestamp": iso_now(),
        "status": "completed",
        "summary": summary,
        "queued": [
            {
                "priority": None,
                "url": f"{r['folder']}/_INDEX.md",
                "reason": f"{r['entries']} entries indexed; "
                          f"{'regenerated' if r['changed'] else 'unchanged'}",
                "timestamp": iso_now(),
            }
            for r in results if r.get("entries", 0) > 0
        ],
        "skipped": [],
        "deferred": [],
        "notes": "",
        "errors": [],
    }
    (run_folder / "index-per-folder.json").write_text(
        json.dumps(payload, indent=2), encoding="utf-8"
    )
    md = [
        f"# index-per-folder — {cycle_id}",
        "",
        f"**Status**: completed  ",
        f"**Timestamp**: {payload['timestamp']}  ",
        f"**Summary**: {summary['folders_scanned']} folders scanned, "
        f"{summary['folders_updated']} regenerated, "
        f"{summary['entries_indexed']} entries total.",
        "",
        "## Queued (folders with an INDEX)",
        "",
        "| Priority | Folder | Entries | Status | Timestamp |",
        "|---|---|---|---|---|",
    ]
    for r in results:
        if r.get("entries", 0) == 0:
            continue
        md.append(
            f"| — | {r['folder']}/ | {r['entries']} | "
            f"{'regenerated' if r['changed'] else 'unchanged'} | {iso_now()} |"
        )
    md += ["", "## Skipped", "", "_(none)_", "", "## Deferred", "", "_(none)_", ""]
    (run_folder / "index-per-folder.md").write_text("\n".join(md), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--topic", required=True)
    ap.add_argument("--vault", default=_default_vault())
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--cycle-id", default=None)
    ap.add_argument("--run-folder", default=None)
    args = ap.parse_args()

    wiki_root = (Path(args.vault) / args.topic / "wiki").resolve()
    if not wiki_root.is_dir():
        print(f"error: wiki root not found: {wiki_root}", file=sys.stderr)
        return 2

    # Process every subfolder containing .md files. Skip hidden + non-dir.
    results = []
    for child in sorted(wiki_root.iterdir()):
        if child.is_dir() and not child.name.startswith("."):
            r = process_folder(child, wiki_root, dry_run=args.dry_run)
            results.append(r)

    folders_scanned = len(results)
    folders_updated = sum(1 for r in results if r.get("changed"))
    entries_indexed = sum(r.get("entries", 0) for r in results)

    print(f"Scanned {folders_scanned} folders; regenerated {folders_updated}; "
          f"indexed {entries_indexed} entries total.")
    for r in results:
        if r.get("entries", 0) > 0:
            state = "↻" if r["changed"] else "·"
            print(f"  {state} {r['folder']}/ ({r['entries']} entries)")

    if args.cycle_id and args.run_folder:
        summary = {
            "folders_scanned": folders_scanned,
            "folders_updated": folders_updated,
            "entries_indexed": entries_indexed,
        }
        emit_cycle_artifacts(Path(args.run_folder), args.cycle_id, results, summary)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
