#!/usr/bin/env python3
"""
Compile a compressed always-loaded _MAP.md for a topic wiki.

This is Asel L2 tier-1 material: a ~3K-token compressed orientation document
loaded into every agent conversation. Per-folder _INDEX.md files are tier-2
(loaded when working in an area); full entries are tier-3 (on demand).

_MAP.md layout:
  - What the wiki is (2-3 sentences)
  - Starting points: HOME.md + hub pages
  - Folder directory: one line per folder — purpose + count + top entries
    (top N by tier, tie-broken by recency)
  - Pointer to concept-gaps + best-practices
  - Pointer to the full _INDEX.md

The file is fully auto-generated from frontmatter + folder READMEs + the
current state of the wiki. Regenerate on every cycle.

Usage
-----
    python wiki-map-compile.py --topic <topic> \\
        --vault llm-wiki/wiki

    # Dry-run:
    python wiki-map-compile.py --topic <topic> --dry-run

    # Cycle-contract JSON emission:
    python wiki-map-compile.py --topic <topic> \\
        --cycle-id 2026-04-24-01 \\
        --run-folder docker/.../_inbox/reports/2026-04-24/2026-04-24-01/

Cycle contract
--------------
When --cycle-id and --run-folder are supplied, writes
<run-folder>/map-compile.json (+ .md) per the schema in
wiki/best-practices/cycle-step-return-format.md. Step name: "map-compile".
"""

from __future__ import annotations


# Path-resolution helpers live in the shared _wiki_config module (single
# source of truth for the multi-wiki config schema). Re-exported under the
# historical private names so the rest of this script is unchanged.
import sys as _sys  # noqa: E402
from pathlib import Path as _ShimPath  # noqa: E402
_sys.path.insert(0, str(_ShimPath(__file__).resolve().parent))
from _wiki_config import default_vault as _default_vault, default_topic as _default_topic, wiki_dir as _wiki_dir, in_sessions as _in_sessions  # noqa: E402
import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# Atomic-write helper (icarus §8).
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _atomic_io import atomic_write_text  # noqa: E402

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
MAP_FILE = "_MAP.md"
MARKER = "<!-- AUTO-GENERATED by wiki-map-compile.py — do not hand-edit -->"

# Top-N entries per folder in the map (tier-sorted)
TOP_N_PER_FOLDER = 5
# Max chars for folder one-liner purpose
MAX_FOLDER_PURPOSE_CHARS = 140

# Per-folder purpose descriptions are sourced PER-TOPIC. Look first in
# `<wiki>/<folder>/README.md` (first non-frontmatter paragraph); fall back to
# the optional override below for folders that don't have a README. The
# override is only used when the topic deliberately ships with predictable
# folder semantics; for user topics, the
# README is authoritative.
FOLDER_PURPOSE_FALLBACK = {
    # Optional. Empty by default; topic-specific defaults can be added here
    # but should always be overridable by a folder README.
}


def folder_purpose(folder_path: Path) -> str:
    """Read a folder's purpose from its README.md (first paragraph after
    optional frontmatter). Falls back to FOLDER_PURPOSE_FALLBACK if no README;
    returns '(no purpose set — add <folder>/README.md)' if neither exists."""
    readme = folder_path / "README.md"
    if readme.exists():
        try:
            text = readme.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
        # Strip frontmatter
        m = FM_RE.match(text)
        if m:
            text = text[m.end():]
        # Find first non-heading non-empty paragraph
        for chunk in re.split(r"\n\s*\n", text):
            chunk = chunk.strip()
            if not chunk or chunk.startswith("#"):
                continue
            # Take first sentence-ish (up to MAX_FOLDER_PURPOSE_CHARS)
            chunk = " ".join(chunk.split())
            if len(chunk) > MAX_FOLDER_PURPOSE_CHARS:
                chunk = chunk[:MAX_FOLDER_PURPOSE_CHARS].rstrip() + "…"
            return chunk
    fallback = FOLDER_PURPOSE_FALLBACK.get(folder_path.name)
    if fallback:
        return fallback
    return f"(no purpose set — add {folder_path.name}/README.md)"


def topic_blurb(wiki_root: Path, topic: str) -> str:
    """Read the topic's scope from <topic>/README.md (the file one level above
    wiki_root). Returns the first non-frontmatter, non-heading paragraph.
    Falls back to a generic line keyed on the topic slug."""
    topic_root = wiki_root.parent
    readme = topic_root / "README.md"
    if readme.exists():
        try:
            text = readme.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
        m = FM_RE.match(text)
        if m:
            text = text[m.end():]
        for chunk in re.split(r"\n\s*\n", text):
            chunk = chunk.strip()
            if not chunk or chunk.startswith("#"):
                continue
            chunk = " ".join(chunk.split())
            return chunk
    return f"A curated knowledge base on **{topic}**. Edit `{topic}/README.md` to set this scope description."


def iso_now() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def parse_frontmatter(text: str) -> dict:
    m = FM_RE.match(text)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        s = line.strip()
        if not s or s.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        fm[key.strip()] = val.strip().strip('"').strip("'")
    return fm


def tier_rank(tier: str) -> int:
    if not tier:
        return 99
    m = re.search(r"\d+", tier)
    if m:
        return int(m.group())
    if tier == "self":
        return 50
    return 99


def collect_folder_entries(folder: Path) -> list[dict]:
    entries = []
    for path in sorted(folder.glob("*.md")):
        if path.name.startswith(".") or path.name == "_INDEX.md":
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        fm = parse_frontmatter(text)
        if not fm.get("title"):
            continue
        entries.append({
            "filename": path.name,
            "title": fm.get("title", path.stem),
            "tier": fm.get("tier", "?"),
            "date": fm.get("date", ""),
            "path": path,
        })
    return entries


def top_entries(entries: list[dict], n: int) -> list[dict]:
    """Return top-N by tier ascending, then date descending."""
    ranked = sorted(
        entries,
        key=lambda e: (tier_rank(e["tier"]), -int(e["date"].replace("-", "") or 0)),
    )
    return ranked[:n]


def collect_root_entries(wiki_root: Path) -> list[dict]:
    entries = []
    for path in sorted(wiki_root.glob("*.md")):
        if path.name.startswith(".") or path.name in {"_INDEX.md", "_MAP.md", "README.md"}:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        fm = parse_frontmatter(text)
        entries.append({
            "filename": path.name,
            "title": fm.get("title", path.stem),
            "tier": fm.get("tier", "?"),
            "date": fm.get("date", ""),
        })
    return entries


def render_map(wiki_root: Path, topic: str, folder_data: dict[str, list[dict]], root_entries: list[dict]) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    total_entries = sum(len(v) for v in folder_data.values()) + len(root_entries)
    blurb = topic_blurb(wiki_root, topic)

    # Hub pages: only link to ones that actually exist in this wiki.
    hub_candidates = [
        ("HOME.md", "landing page, what this wiki is and where to begin"),
        ("concept-gaps-things-mentioned-not-yet-covered.md", "things mentioned but not yet covered, priority-sorted"),
    ]
    hub_lines = []
    for fname, descr in hub_candidates:
        if (wiki_root / fname).exists():
            hub_lines.append(f"- [**{fname}**](./{fname}) — {descr}")

    lines = [
        "---",
        f'title: "MAP — {topic} wiki orientation"',
        f"date: {today}",
        "source_url: internal://auto-generated/MAP",
        "ingested_by: wiki-map-compile.py",
        "tier: self",
        "confidence: high",
        f"last_reviewed: {today}",
        "review_after: 2026-10-24",
        "tags: [map, index, orientation, auto-generated, always-loaded]",
        "---",
        "",
        MARKER,
        "",
        f"# MAP — {topic} wiki",
        "",
        f"**Compressed orientation map.** {total_entries} entries total, across {len(folder_data)} folders + root. Designed to be loaded into every conversation. For comprehensive listings use the full [`_INDEX.md`](../_INDEX.md) at the topic root. For per-folder detail use `<folder>/_INDEX.md`. For search use `qmd query \"…\"`.",
        "",
        "## What this wiki is",
        "",
        blurb,
        "",
        "## Start here",
        "",
    ]
    if hub_lines:
        lines.extend(hub_lines)
    else:
        lines.append("_(No hub pages found yet — add a HOME.md to introduce this wiki.)_")
    lines.extend([
        "",
        "## Folders",
        "",
    ])

    for folder_name in sorted(folder_data.keys()):
        entries = folder_data[folder_name]
        purpose = folder_purpose(wiki_root / folder_name)
        tops = top_entries(entries, TOP_N_PER_FOLDER)
        lines.append(f"### [`{folder_name}/`](./{folder_name}/_INDEX.md) — {len(entries)} entries")
        lines.append("")
        lines.append(purpose)
        lines.append("")
        lines.append("Top entries:")
        for e in tops:
            tier_badge = f" _[T{e['tier']}]_" if e['tier'] and e['tier'] != '?' else ""
            lines.append(f"- [{e['title']}](./{folder_name}/{e['filename']}){tier_badge}")
        lines.append("")

    # Root-level non-hub entries (anything at the wiki root that isn't a recognised hub).
    # The hub set includes the framework-level pages we always exclude from the
    # "other entries" listing; topic-specific hubs are listed via the "Start here"
    # block at the top, sourced from hub_lines/hub_candidates.
    hub_names = {"HOME.md",
                 "concept-gaps-things-mentioned-not-yet-covered.md",
                 "_INDEX.md", "_MAP.md"}
    other_root = [e for e in root_entries if e["filename"] not in hub_names]
    if other_root:
        lines.append("### Root-level entries")
        lines.append("")
        lines.append(f"{len(other_root)} additional entries live at the wiki root (hubs + special pages outside the folder taxonomy).")
        lines.append("")
        for e in top_entries(other_root, TOP_N_PER_FOLDER):
            tier_badge = f" _[T{e['tier']}]_" if e['tier'] and e['tier'] != '?' else ""
            lines.append(f"- [{e['title']}](./{e['filename']}){tier_badge}")
        lines.append("")

    lines.extend([
        "## How to use this map",
        "",
        "- **Orienting**: start with the Start-here block above",
        "- **Going deep on an area**: click through to that folder's `_INDEX.md` for the full scannable list",
        "- **Finding something specific**: `/wiki-search \"<terms>\"` (hybrid BM25 + vector + LLM rerank)",
        "- **Missing something**: check [concept gaps](./concept-gaps-things-mentioned-not-yet-covered.md) — if it's on that list, we've noticed; if not, it's a new gap to file",
        "",
        "## The 4 commands",
        "",
        "- `/wiki-cycle` — the orchestrator. Mode flags: `--lint-only`, `--ingest-only`, `--discover-only`, `--full`, `--prompt-for-urls`, `--report-only`, `--refresh-only`, `--claims-only`. 90% of wiki work.",
        "- `/wiki-update <url(s)>` — ad-hoc ingest (1 URL = fetch now; multiple = queue to pending)",
        "- `/wiki-search <query>` — read",
        "- `/wiki-init <topic>` — one-time scaffold",
        "",
        "Other `/wiki-*` skills are internal — invoked by `/wiki-cycle`, not by you directly.",
        "",
        "This MAP is auto-regenerated by `wiki-map-compile.py`. Do not hand-edit within the AUTO-GENERATED markers — changes will be overwritten.",
    ])

    return "\n".join(lines) + "\n"


def process(wiki_root: Path, topic: str, dry_run: bool = False) -> dict:
    folder_data = {}
    # Container folders (research/, project/) hold subfolders instead of direct
    # .md entries. Walk one level deeper into those. sessions/ is NON-CURATED
    # (working + episodic memory) and is excluded from the map entirely.
    CONTAINER_FOLDERS = {"research", "project"}
    for child in sorted(wiki_root.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        if child.name == "sessions":
            continue  # non-curated working/episodic memory — not orientation knowledge
        entries = collect_folder_entries(child)
        if entries:
            folder_data[child.name] = entries
        elif child.name in CONTAINER_FOLDERS:
            # Container folder: enumerate ALL descendant category folders at ANY depth,
            # keyed by path relative to wiki_root. Recurses so deeply-nested clusters
            # (e.g. project/components/hints/techniques/) still appear in the map.
            for subfolder in sorted(d for d in child.rglob("*") if d.is_dir()):
                rel = subfolder.relative_to(wiki_root)
                if any(part.startswith(("_", ".")) for part in rel.parts):
                    continue
                sub_entries = collect_folder_entries(subfolder)
                if sub_entries:
                    folder_data[rel.as_posix()] = sub_entries
    root_entries = collect_root_entries(wiki_root)

    new_content = render_map(wiki_root, topic, folder_data, root_entries)
    map_path = wiki_root / MAP_FILE
    existing = map_path.read_text(encoding="utf-8") if map_path.exists() else ""

    def _strip_volatile(s: str) -> str:
        return re.sub(r"^(date|last_reviewed):.*$", "", s, flags=re.MULTILINE)

    changed = _strip_volatile(existing) != _strip_volatile(new_content)
    if changed and not dry_run:
        atomic_write_text(map_path, new_content)

    char_count = len(new_content)
    approx_tokens = char_count // 4  # rough heuristic

    return {
        "folders": len(folder_data),
        "entries_total": sum(len(v) for v in folder_data.values()) + len(root_entries),
        "char_count": char_count,
        "approx_tokens": approx_tokens,
        "changed": changed,
        "path": str(map_path),
    }


def emit_cycle_artifacts(run_folder: Path, cycle_id: str, result: dict) -> None:
    run_folder.mkdir(parents=True, exist_ok=True)
    payload = {
        "skill": "wiki-map-compile",
        "cycle_id": cycle_id,
        "step": "map-compile",
        "timestamp": iso_now(),
        "status": "completed",
        "summary": {
            "folders": result["folders"],
            "entries_total": result["entries_total"],
            "char_count": result["char_count"],
            "approx_tokens": result["approx_tokens"],
            "changed": result["changed"],
        },
        "queued": [{
            "priority": None,
            "url": "wiki/_MAP.md",
            "reason": f"{result['entries_total']} entries across {result['folders']} folders; "
                      f"{'regenerated' if result['changed'] else 'unchanged'}; "
                      f"~{result['approx_tokens']} tokens",
            "timestamp": iso_now(),
        }],
        "skipped": [],
        "deferred": [],
        "notes": "",
        "errors": [],
    }
    atomic_write_text(run_folder / "map-compile.json", json.dumps(payload, indent=2))
    md = [
        f"# map-compile — {cycle_id}",
        "",
        f"**Status**: completed  ",
        f"**Timestamp**: {payload['timestamp']}  ",
        f"**Summary**: {result['folders']} folders, {result['entries_total']} entries, "
        f"~{result['approx_tokens']} tokens, "
        f"{'regenerated' if result['changed'] else 'unchanged'}.",
        "",
        "## Queued",
        "",
        "| Priority | URL | Reason | Timestamp |",
        "|---|---|---|---|",
        f"| — | wiki/_MAP.md | {result['entries_total']} entries / {result['approx_tokens']} tokens "
        f"({'regenerated' if result['changed'] else 'unchanged'}) | {iso_now()} |",
        "",
        "## Skipped",
        "",
        "_(none)_",
        "",
        "## Deferred",
        "",
        "_(none)_",
        "",
    ]
    atomic_write_text(run_folder / "map-compile.md", "\n".join(md))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--topic", required=True)
    ap.add_argument("--vault", default=None,
                    help="Vault-of-topic-roots override (legacy <vault>/<topic>/wiki join — "
                         "the dir that CONTAINS the topic folder, e.g. 'notebooks/'). NOT the "
                         "same shape as wiki-promote.py's own --vault (which is the topic's "
                         "wiki/ dir itself) — both shapes are now auto-recognized by "
                         "_wiki_config.wiki_dir(), but omitting --vault entirely and relying on "
                         "registry-based resolution is the simplest correct default.")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--cycle-id", default=None)
    ap.add_argument("--run-folder", default=None)
    args = ap.parse_args()

    wiki_root = Path(_wiki_dir(args.topic, vault=args.vault)).resolve()
    if not wiki_root.is_dir():
        print(f"error: wiki root not found: {wiki_root}", file=sys.stderr)
        return 2

    result = process(wiki_root, args.topic, dry_run=args.dry_run)
    state = "↻ regenerated" if result["changed"] else "· unchanged"
    print(f"_MAP.md: {state}  |  {result['entries_total']} entries across {result['folders']} folders  |  ~{result['approx_tokens']} tokens")

    if args.cycle_id and args.run_folder:
        emit_cycle_artifacts(Path(args.run_folder), args.cycle_id, result)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
