#!/usr/bin/env python3
"""
Initialize a new topic wiki — creates folder structure + templated README.

Usage:
    python3 wiki-init.py --topic <name> --description "<one-line scope>"
    python3 wiki-init.py --topic <name> --description "..." --vault /custom/vault

If --vault is omitted, defaults to /shared/openclaw/vault/wikis (the OpenClaw
container path). Both --topic and --description are required because the
slash command body is responsible for asking the user when they're missing.

This script does NOT have its own conversational flow — it's a pure scaffolder.
The conversational discovery (propose topic/description from a chat) happens
in the /wiki-init slash command.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

DEFAULT_VAULT = "/shared/openclaw/vault/wikis"

SLUG_RE = re.compile(r"[^a-z0-9]+")

# Files that get `<topic>` and `<YYYY-MM-DD>` placeholder substitution.
# Other files (framework contracts, user-guide) are copied verbatim because
# their `<topic>` strings are doc-generic, not template placeholders.
TEMPLATED_FILES = {
    "README.md",
    "wiki/HOME.md",
    "_config/feeds.md",
}


def find_topic_template():
    """Locate topic-template directory by trying known relative locations."""
    here = Path(__file__).resolve()
    candidates = [
        here.parent / "topic-template",                                    # colocated
        here.parents[6] / "workflows" / "llm-wiki" / "topic-template",     # in-repo
        here.parents[1] / "topic-template",                                # package layout
    ]
    for c in candidates:
        if c.exists() and (c / "wiki" / "HOME.md").exists():
            return c
    return None


def slugify(text):
    s = (text or "").lower().strip()
    s = SLUG_RE.sub("-", s).strip("-")
    return s or "untitled"


VAULT_README_TEMPLATE = """# Wikis Vault

This folder holds **topic-based research wikis** managed by the `research-wiki` skill.

Each subfolder is a topic — a long-running research area you curate over time. Inside a topic:

```
<topic>/
├── README.md        # Scope, ingest rules
├── _INDEX.md         # Auto-generated by wiki-index.py
├── raw/             # Verbatim originals (URLs fetched, transcripts, PDFs)
├── wiki/            # Curated .md files, organized by concept folder
├── answers/         # Agent-authored answers filed back here
└── _inbox/
    ├── pending/     # Queue items waiting to be processed
    ├── done/        # Successfully processed
    └── failed/      # Failed with .error sidecars
```

## Creating a new topic

Use the `/wiki-init` slash command (Claude Code) or call `wiki-init.py` directly:

```bash
python3 wiki-init.py --topic my-topic --description "What this topic is about"
```

## Managing wikis

- `/wiki-update` — add or update content (URL, file, video, or session synthesis)
- `/wiki-list` — manage the pending ingestion list (add / process / show)
- `/wiki` — show a topic's INDEX
- `/wiki-search` — grep across a topic's wiki

See the `research-wiki` skill SKILL.md for full details.
"""


TOPIC_README_TEMPLATE = """# {title} Wiki

**Topic**: `{topic}`
**Description**: {description}
**Started**: {date}

---

## Scope — what belongs here

✅ **In scope**:
- _Edit this section after creation_

❌ **Out of scope**:
- _Edit this section after creation_

---

## Layout

```
{topic}/
├── README.md       ← this file
├── _INDEX.md        ← auto-generated, do not edit
├── raw/            ← original verbatim sources
├── wiki/           ← curated .md files, organized by concept folder
├── answers/        ← agent-authored answers (write-back loop)
└── _inbox/
    ├── pending/    ← queued for ingestion
    ├── done/       ← successfully processed
    └── failed/     ← processing errors
```

---

## Adding content

```bash
# Direct add (URL, file, or YouTube)
/wiki-update

# Queue for later batch processing
/wiki-list add <url>
/wiki-list process
```

The `wiki/` folder is canonical. `_INDEX.md` is regenerated automatically.

---

## Curation rules

1. Folder hierarchy is the primary filter — file by concept, not by source type
2. Every file gets frontmatter (title, date, source_url, raw_path, ingested_by, tags)
3. One concept per file
4. Don't edit `_INDEX.md` — it's regenerated
5. Quality > word count (raw transcripts/originals stay in `raw/` if you need depth)
"""


def copy_template_tree(template_dir: Path, topic_root: Path, topic_slug: str, description: str):
    """Walk topic-template and copy every file into the new topic, with placeholder
    substitution for the small set of templated files."""
    today = datetime.now().strftime("%Y-%m-%d")
    review_after = datetime.now().replace(year=datetime.now().year + 1).strftime("%Y-%m-%d")

    copied = 0
    for src in template_dir.rglob("*"):
        if not src.is_file():
            continue
        rel = src.relative_to(template_dir).as_posix()
        dest = topic_root / rel
        dest.parent.mkdir(parents=True, exist_ok=True)

        if rel in TEMPLATED_FILES:
            content = src.read_text(encoding="utf-8")
            content = content.replace("<topic>", topic_slug)
            content = content.replace("<YYYY-MM-DD>", today)
            # HOME.md frontmatter has placeholder dates 2026-01-01 / 2027-01-01
            if rel == "wiki/HOME.md":
                content = content.replace("2026-01-01", today)
                content = content.replace("2027-01-01", review_after)
            # Inject description into README scope-line if present
            if rel == "README.md" and description:
                content = content.replace(
                    "(Fill in — what's in-scope for this wiki, what's out-of-scope. Keep it specific; overly-broad scope leads to topic bleed.)",
                    description.strip(),
                )
            dest.write_text(content, encoding="utf-8")
        else:
            shutil.copy2(src, dest)
        copied += 1
    return copied


def init_topic(vault_root, topic, description):
    vault_root = Path(vault_root)
    topic_slug = slugify(topic)
    topic_root = vault_root / topic_slug

    if topic_root.exists():
        print(f"ERROR: topic already exists at {topic_root}", file=sys.stderr)
        return 1

    # Create vault root + top-level README if missing
    if not vault_root.exists():
        vault_root.mkdir(parents=True, exist_ok=True)
        print(f"Created vault root: {vault_root}")
    vault_readme = vault_root / "README.md"
    if not vault_readme.exists():
        vault_readme.write_text(VAULT_README_TEMPLATE, encoding="utf-8")
        print(f"Wrote vault README: {vault_readme}")

    # Locate topic-template (the rich scaffold)
    template_dir = find_topic_template()

    # Create topic structure (always — guarantees baseline even if template missing)
    subdirs = [
        "wiki",
        "raw",
        "answers",
        "_inbox/pending",
        "_inbox/done",
        "_inbox/failed",
    ]
    for sub in subdirs:
        (topic_root / sub).mkdir(parents=True, exist_ok=True)
    print(f"Created topic structure: {topic_root}")

    if template_dir:
        copied = copy_template_tree(template_dir, topic_root, topic_slug, description)
        print(f"Copied {copied} template files from {template_dir}")
    else:
        print("Warning: topic-template not found — falling back to bare README")
        title = " ".join(w.capitalize() for w in topic_slug.replace("-", " ").split())
        readme_content = TOPIC_README_TEMPLATE.format(
            title=title,
            topic=topic_slug,
            description=description,
            date=datetime.now().strftime("%Y-%m-%d"),
        )
        (topic_root / "README.md").write_text(readme_content, encoding="utf-8")

    # Generate initial _INDEX.md
    index_script = Path(__file__).parent / "wiki-index.py"
    if index_script.exists():
        result = subprocess.run(
            [sys.executable, str(index_script), "--topic", topic_slug, "--vault", str(vault_root)],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            print(f"Generated initial _INDEX.md")
        else:
            print(f"Warning: INDEX generation failed: {result.stderr.strip()}")

    print()
    print(f"✓ Topic '{topic_slug}' ready at {topic_root}")
    print(f"  Next: edit _config/feeds.md, then /wiki-update <url> for first entries")
    return 0


def main():
    parser = argparse.ArgumentParser(description="Initialize a new wiki topic")
    parser.add_argument("--topic", required=True, help="Topic name (will be slugified)")
    parser.add_argument("--description", required=True, help="One-line scope description")
    parser.add_argument("--vault", default=DEFAULT_VAULT, help=f"Vault root (default: {DEFAULT_VAULT})")
    args = parser.parse_args()
    return init_topic(args.vault, args.topic, args.description)


if __name__ == "__main__":
    sys.exit(main())
